component_management:
  individual_components:
    - component_id: calculator
      paths:
        - "calculator/"
    - component_id: smiles
      paths:
        - "smiles/"

comment:
  layout: "header, diff, flags, components"
