name: Workflow for Codecov Components
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage for simple calculator
        run: pytest --cov calculator.simple
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          move_coverage_to_trash: true
          flags: simple-calculator

      - name: Run tests and collect coverage for complex calculator
        run: pytest --cov calculator.complex
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          move_coverage_to_trash: true
          flags: complex-calculator

      - name: Run tests and collect coverage for smiles
        run: pytest --cov smiles
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          move_coverage_to_trash: true
          flags: smiles

      - name: Run mutation testing
        run: mutmut run

      - name: Show mutation testing results
        if: always()
        run: mutmut results

      - name: Show xml results
        if: always()
        run: mutmut junitxml
